### ISSUE TITLE
Error when launching pipeline on Dagster UI

### ISSUE THREAD

**Issue by l1uzz3** [sspaeti-com/practical-data-engineering#5]
**When trying to run any pipeline from Dagster UI I get this error:**

`Operation name: PipelineRunLogsSubscription

Message: BaseObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: `

![image](https://github.com/user-attachments/assets/e745cfb0-0bea-4f6b-9d75-4aa8130e52c6)

**Please help**

LATER EDIT & FIX: i downgraded watchdog into the terminal pip install watchdog==0.10.4 then it worked

**Comment by sspaeti** [comment]
Thanks for letting me know. I will check in a while to see if Watchdog is still funky or if that has been resolved.
